### PR TITLE
Spanish es_ES translation

### PR DESCRIPTION
**Pull request by xyulex**
Hello,

I just translated Nested Pages into Spanish from Spain.

Thanks :)

### CODE REVIEW

**Comment by xyulex** [comment]
.

**Comment by xyulex** [comment]
Is anybody out there?

**Comment by kylephillips** [comment]
I'm here. I apologize for the delay. This will be merged in with the next update. I really appreciate the translation.

**Comment by xyulex** [comment]
Glad to hear it!

**Pull request merged**
